### ISSUE TITLE
incomplete type and set size of ctx

### ISSUE THREAD

**Issue by cryptofuture** [wburgers/Session-Binding-Proxy#11]
```
debian/extra/Session-Binding-Proxy/nginx_session_binding_proxy_module/ngx_http_session_binding_proxy_module.c:190:43: error: dereferencing pointer to incomplete type 'SSL_SESSION {aka struct ssl_session_st}'
    uint64_t* mkey = (uint64_t*)ssl_session->master_key;
                                           ^~
debian/extra/Session-Binding-Proxy/nginx_session_binding_proxy_module/ngx_http_session_binding_proxy_module.c: In function 'ngx_http_session_binding_proxy_aes_encrypt':
debian/extra/Session-Binding-Proxy/nginx_session_binding_proxy_module/ngx_http_session_binding_proxy_module.c:652:20: error: storage size of 'ctx' isn't known
     EVP_CIPHER_CTX ctx;
                    ^~~
debian/extra/Session-Binding-Proxy/nginx_session_binding_proxy_module/ngx_http_session_binding_proxy_module.c:652:20: error: unused variable 'ctx' [-Werror=unused-variable]
debian/extra/Session-Binding-Proxy/nginx_session_binding_proxy_module/ngx_http_session_binding_proxy_module.c: In function 'ngx_http_session_binding_proxy_aes_decrypt':
debian/extra/Session-Binding-Proxy/nginx_session_binding_proxy_module/ngx_http_session_binding_proxy_module.c:736:20: error: storage size of 'ctx' isn't known
     EVP_CIPHER_CTX ctx;
                    ^~~

```

**Comment by wburgers** [comment]
This is a compile time error right?
Which OS and build tools and nginx version are you using?
I'll try to recreate this and fix it.
Thanks for reporting this one!

**Comment by cryptofuture** [comment]
Bionic ubuntu 18.04 and nginx-1.15.6 mainline

**Comment by wburgers** [comment]
Thank you! I can indeed reproduce this and will try to work on it next weekend.

**Comment by wburgers** [comment]
I fixed the compile time errors, so the code is compiling again, but I haven't tested it yet.
I will test the module sometime this week, but I need to set up a test server with certificate and all (annoying work that I haven't got automated...)

**Comment by cryptofuture** [comment]
@wburgers Could you provide compile fix in a separate branch or in master?

**Comment by wburgers** [comment]
Yeah, it is over here:
https://github.com/wburgers/Session-Binding-Proxy/tree/openssl-1.1.x

**Comment by cryptofuture** [comment]
I was able to build in pbuilder with bionic and xenial in local env, but it turns out now I failing a build on launchpad even with xenial, since `-Werror=implicit-function-declaration` exposed there.
https://launchpadlibrarian.net/398872404/buildlog_ubuntu-xenial-amd64.nginx_1.15.6-1-ppa7~xenial_BUILDING.txt.gz

**Comment by cryptofuture** [comment]
UPD: Check #12

**Comment by wburgers** [comment]
That error is because my fix was not backwards compatible.
trying to build for older OpenSSL versions which don't have the function SSL_SESSION_get_master_key will result in this error.
I've found some example code that can handle both older and newer OpenSSL master key extraction.

Please try again with the latest code on the same branch.
https://github.com/wburgers/Session-Binding-Proxy/tree/openssl-1.1.x

**Comment by wburgers** [comment]
@cryptofuture I take it that this has resolved your issue?
If that is the case, I will merge this to master.
